<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHMPdfw5\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHMPdfw5/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHMPdfw5.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHMPdfw5\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerHMPdfw5\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'HMPdfw5',
    'container.build_id' => 'c5430ad8',
    'container.build_time' => 1560800760,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHMPdfw5');
