<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Supplement extends \App\Entity\Supplement implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Supplement' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Supplement' . "\0" . 'derniereMinute', '' . "\0" . 'App\\Entity\\Supplement' . "\0" . 'optionAnnulation', '' . "\0" . 'App\\Entity\\Supplement' . "\0" . 'horraireDemande', '' . "\0" . 'App\\Entity\\Supplement' . "\0" . 'navetteNuit', '' . "\0" . 'App\\Entity\\Supplement' . "\0" . 'priseDomicile', '' . "\0" . 'App\\Entity\\Supplement' . "\0" . 'maiDecembre', '' . "\0" . 'App\\Entity\\Supplement' . "\0" . 'facture'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Supplement' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Supplement' . "\0" . 'derniereMinute', '' . "\0" . 'App\\Entity\\Supplement' . "\0" . 'optionAnnulation', '' . "\0" . 'App\\Entity\\Supplement' . "\0" . 'horraireDemande', '' . "\0" . 'App\\Entity\\Supplement' . "\0" . 'navetteNuit', '' . "\0" . 'App\\Entity\\Supplement' . "\0" . 'priseDomicile', '' . "\0" . 'App\\Entity\\Supplement' . "\0" . 'maiDecembre', '' . "\0" . 'App\\Entity\\Supplement' . "\0" . 'facture'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Supplement $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getDerniereMinute(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDerniereMinute', []);

        return parent::getDerniereMinute();
    }

    /**
     * {@inheritDoc}
     */
    public function setDerniereMinute(bool $derniereMinute): \App\Entity\Supplement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDerniereMinute', [$derniereMinute]);

        return parent::setDerniereMinute($derniereMinute);
    }

    /**
     * {@inheritDoc}
     */
    public function getOptionAnnulation(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOptionAnnulation', []);

        return parent::getOptionAnnulation();
    }

    /**
     * {@inheritDoc}
     */
    public function setOptionAnnulation(bool $optionAnnulation): \App\Entity\Supplement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOptionAnnulation', [$optionAnnulation]);

        return parent::setOptionAnnulation($optionAnnulation);
    }

    /**
     * {@inheritDoc}
     */
    public function getHorraireDemande(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHorraireDemande', []);

        return parent::getHorraireDemande();
    }

    /**
     * {@inheritDoc}
     */
    public function setHorraireDemande(bool $horraireDemande): \App\Entity\Supplement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHorraireDemande', [$horraireDemande]);

        return parent::setHorraireDemande($horraireDemande);
    }

    /**
     * {@inheritDoc}
     */
    public function getNavetteNuit(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNavetteNuit', []);

        return parent::getNavetteNuit();
    }

    /**
     * {@inheritDoc}
     */
    public function setNavetteNuit(bool $navetteNuit): \App\Entity\Supplement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNavetteNuit', [$navetteNuit]);

        return parent::setNavetteNuit($navetteNuit);
    }

    /**
     * {@inheritDoc}
     */
    public function getPriseDomicile(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPriseDomicile', []);

        return parent::getPriseDomicile();
    }

    /**
     * {@inheritDoc}
     */
    public function setPriseDomicile(bool $priseDomicile): \App\Entity\Supplement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPriseDomicile', [$priseDomicile]);

        return parent::setPriseDomicile($priseDomicile);
    }

    /**
     * {@inheritDoc}
     */
    public function getMaiDecembre(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMaiDecembre', []);

        return parent::getMaiDecembre();
    }

    /**
     * {@inheritDoc}
     */
    public function setMaiDecembre(bool $maiDecembre): \App\Entity\Supplement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMaiDecembre', [$maiDecembre]);

        return parent::setMaiDecembre($maiDecembre);
    }

    /**
     * {@inheritDoc}
     */
    public function getFacture(): ?\App\Entity\Facture
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFacture', []);

        return parent::getFacture();
    }

    /**
     * {@inheritDoc}
     */
    public function setFacture(?\App\Entity\Facture $facture): \App\Entity\Supplement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFacture', [$facture]);

        return parent::setFacture($facture);
    }

}
